orbs:
  maven: circleci/maven@1.3.0
version: 2.1
machine:
  java:
    version: 'oraclejdk8'
build-and-publish:
    jobs:
      - publish:   
          filters:
            branches:
              only: master
workflows:
  maven_test:
    jobs:
      - maven/test:
          command: '-X verify'
