orbs:
  maven: circleci/maven@1.3.0
  codecov: codecov/codecov@3.1.1
version: 2.1
machine:
  java:
    version: 'oraclejdk8'
    
build-and-publish:
    jobs:
      - publish:   
          filters:
            branches:
              only: master


steps:
  - run:
      name: test
      command: test
  - codecov/upload:
          file: {{ coverage_report_filepath }}

Run-With-Node:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: install and run tests
          command: |
            yarn install && yarn test
      - codecov/upload:
          file: './coverage/clover.xml'
          token: a7a5df63-codcov-token-4278vh38
          
workflows:
  maven_test:
    jobs:
      - maven/test:
          command: '-X verify'
 