orbs:
  maven: circleci/maven@1.3.0
  codecov: codecov/codecov@3.1.1
version: 2.1
machine:
  java:
    version: 'oraclejdk8'
build-and-publish:
    jobs:
      - publish:   
          filters:
            branches:
              only: master

  
steps:
  - run:
      name: test
      command: test
  - run:
    name: Code Coverage
    command: curl -Os https://uploader.codecov.io/latest/linux/codecov; chmod +x codecov; ./codecov


workflows:
  maven_test:
    jobs:
      - maven/test:
          command: '-X verify'
      


