orbs:
  maven: circleci/maven@1.3.0
  codecov: codecov/codecov@3.1.1
  node: circleci/node@4.7.0
version: 2.1
machine:
  java:
    version: 'oraclejdk8'
    
build-and-publish:
    jobs:
      - publish:   
          filters:
            branches:
              only: master


steps:
  - run:
      name: test
      command: test


workflows:
  maven_test:
    jobs:
      - maven/test:
          command: '-X verify'
  upload-to-codecov:
    jobs:
      - node/test:
          post-steps:
            - codecov/upload
 