orbs:
  maven: circleci/maven@1.3.0
  codecov: codecov/codecov@3.1.1
version: 2.1
machine:
  java:
    version: 'oraclejdk8'
build-and-publish:
    jobs:
      - publish:   
          filters:
            branches:
              only: master
    steps:
      - codecov/upload:
          file: {{ coverage_report_filepath }}


steps:
  - run:
      name: test
      command: test
  - run:


workflows:
  maven_test:
    jobs:
      - maven/test:
          command: '-X verify'
 
      


